/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.translate.view;

/**
 *
 * @author JoseRichard
 */
public final class FrmFacebook extends javax.swing.JFrame {

    /**
     * Creates new form FrmFacebook
     */
    public FrmFacebook() {
        initComponents();
        transparenciaButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Password = new javax.swing.JLabel();
        desaparecerUsuario = new javax.swing.JLabel();
        Password1 = new javax.swing.JPasswordField();
        Registred = new javax.swing.JButton();
        Usario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1350, 950));
        setResizable(false);
        getContentPane().setLayout(null);

        Password.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Password.setForeground(new java.awt.Color(204, 204, 204));
        Password.setText("Password");
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordMouseClicked(evt);
            }
        });
        getContentPane().add(Password);
        Password.setBounds(540, 300, 130, 40);

        desaparecerUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        desaparecerUsuario.setForeground(new java.awt.Color(204, 204, 204));
        desaparecerUsuario.setText("Email or phone number");
        desaparecerUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desaparecerUsuarioMouseClicked(evt);
            }
        });
        getContentPane().add(desaparecerUsuario);
        desaparecerUsuario.setBounds(540, 250, 280, 40);

        Password1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        getContentPane().add(Password1);
        Password1.setBounds(520, 300, 350, 40);

        Registred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistredActionPerformed(evt);
            }
        });
        getContentPane().add(Registred);
        Registred.setBounds(530, 350, 340, 50);
        getContentPane().add(Usario);
        Usario.setBounds(520, 250, 350, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Facebook1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 930);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void desaparecerUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desaparecerUsuarioMouseClicked
        desaparecerUsuario.setVisible(false);
    }//GEN-LAST:event_desaparecerUsuarioMouseClicked

    private void PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseClicked
        Password.setVisible(false);
    }//GEN-LAST:event_PasswordMouseClicked

    private void RegistredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistredActionPerformed
      FrmTranslateAppLogin frmTranslateAppLogin = new FrmTranslateAppLogin();
        frmTranslateAppLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegistredActionPerformed
      public void transparenciaButton(){
          Registred.setOpaque(false);
          Registred.setContentAreaFilled(false);
          Registred.setBorderPainted(false);
      }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFacebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFacebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFacebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFacebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFacebook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField Password1;
    private javax.swing.JButton Registred;
    private javax.swing.JTextField Usario;
    private javax.swing.JLabel desaparecerUsuario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
