/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.translate.view;

/**
 *
 * @author JoseRichard
 */
public class FrmGoogle2 extends javax.swing.JFrame {

    public int a=1;
    public String contraseña;
    /**
     * Creates new form FrmGoogle2
     */
    public FrmGoogle2() {
        initComponents();
        transparenciaButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contraseñaCodigo = new javax.swing.JPasswordField();
        contraseñaSinCodigo = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        botonNext = new javax.swing.JButton();
        NoShow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(789, 810));
        setResizable(false);
        getContentPane().setLayout(null);

        contraseñaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(contraseñaCodigo);
        contraseñaCodigo.setBounds(170, 330, 430, 22);
        getContentPane().add(contraseñaSinCodigo);
        contraseñaSinCodigo.setBounds(170, 330, 420, 22);

        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton1.setText("Show Password");
        jRadioButton1.setFocusTraversalPolicyProvider(true);
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseExited(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(160, 390, 190, 30);

        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 380, 190, 40);

        botonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNextActionPerformed(evt);
            }
        });
        getContentPane().add(botonNext);
        botonNext.setBounds(520, 630, 100, 40);

        NoShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/contraseña.jpg"))); // NOI18N
        NoShow.setText("jLabel1");
        getContentPane().add(NoShow);
        NoShow.setBounds(0, 0, 790, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNextActionPerformed
        FrmTranslateAppLogin frmTranslateAppLogin = new FrmTranslateAppLogin();
        frmTranslateAppLogin.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_botonNextActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if(a==1){
            contraseñaCodigo.setVisible(false);
            a--;
            }
        else if (a==0){
            contraseñaCodigo.setVisible(true);
            a++;
            }
               
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseReleased
        
    }//GEN-LAST:event_jRadioButton1MouseReleased

    private void jRadioButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseExited
       
    }//GEN-LAST:event_jRadioButton1MouseExited

    private void jRadioButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MousePressed
                

    }//GEN-LAST:event_jRadioButton1MousePressed

    private void contraseñaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaCodigoActionPerformed
       
    }//GEN-LAST:event_contraseñaCodigoActionPerformed

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
       
    }//GEN-LAST:event_jRadioButton1MouseClicked
    
    public void transparenciaButton(){
       botonNext.setOpaque(false);
       botonNext.setContentAreaFilled(false);
       botonNext.setBorderPainted(false);   
          
      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGoogle2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGoogle2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGoogle2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGoogle2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGoogle2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NoShow;
    private javax.swing.JButton botonNext;
    private javax.swing.JPasswordField contraseñaCodigo;
    private javax.swing.JTextField contraseñaSinCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
